dist: trusty
sudo: required
language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install autoconf automake autopoint libtool libpam0g-dev bison flex gettext check
before_script:
  - ./autogen.sh
script:
  - ./configure && make
  - make check || { ! test -f tests/test-suite.log || cat tests/test-suite.log; exit 1; }
  - sudo ./src/loadkeys ./data/keymaps/i386/qwerty/us.map
  - make distcheck
